name: music_player
description: A personal music player
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.38
  file_picker: ^6.1.1
  path_provider: ^2.0.14
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0